language: node_js
node_js:
  - "10.9"
 
branches:
  only:
    - master
 
cache:
  directories:
    - node_modules
 
script:
  - npm run build.prod
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 2WyP3riLggi42k2Ztg3AsQ
  local_dir: dist
  on:
    branch: master
