language: node_js
node_js:
    - "10.9"

branches:
    only:
        - master
        - gh-pages

cache:
    directories:
        - node_modules

script:
    - npm run build.prod

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/angular-clash-royale
    on:
        branch: master
